services:
  prisma-db:
    build:
      context: .
      dockerfile: ./Local.Dockerfile
    container_name: prisma-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: uN3D1DPbO0vq0HDRvilvXiON7z6FWJhv
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "4820:5432"
    networks:
      - prisma_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    command: >
      postgres -c max_connections=1000
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  prisma_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
