#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE db0;
  CREATE DATABASE db1;
  CREATE DATABASE db2;
  CREATE DATABASE db3;
  GRANT ALL PRIVILEGES ON DATABASE db0 TO $POSTGRES_USER
  GRANT ALL PRIVILEGES ON DATABASE db1 TO $POSTGRES_USER
  GRANT ALL PRIVILEGES ON DATABASE db2 TO $POSTGRES_USER
  GRANT ALL PRIVILEGES ON DATABASE db3 TO $POSTGRES_USER
EOSQL